ops:
  find_pdfs:
    config:
      input_path: landing-bay
  store_images:
    config:
      base_dir: pdf-pages
  store_text:
    config:
      index: ocr_text

resources:
  prometheus:
    config:
      gateway: localhost:9091
  fs:
    config:
      endpoint_url: http://localhost:9000
  search_index:
    config:
      endpoint_url: localhost:9200
      use_ssl: False
      verify_certs: False
      chunk_size: 10000
      thread_count: 16
      queue_size: 16